name: Deploy Petzon API to EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
          
          scp -o StrictHostKeyChecking=no -i private_key \
            target/petzonapi-0.0.1-SNAPSHOT.jar \
            ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ec2-user/

          ssh -o StrictHostKeyChecking=no -i private_key \
            ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} \
            "sudo systemctl restart minha-app.service"
